name: multi-stage-bicep-deploy
concurrency: concurrency-token

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  # Build the application
  build:
    uses: ./.github/workflows/build-aspnet-app.yml
  
  # Lint bicep code
  lint:
    uses: ./.github/workflows/lint.yml

  # Deploy to the test environment.
  deploy-test:
    uses: ./.github/workflows/deploy-to-environment.yml
    needs: [build, lint]
    with:
      environmentType: Test
      resourceGroupName: intrinsic-rg
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Deploy to the production environment.
  deploy-production:
    uses: ./.github/workflows/deploy-to-environment.yml
    # equivalent to array expression [lint, build, deploy-test]
    needs: 
    - lint
    - build
    - deploy-test
    with:
      environmentType: Prod
      resourceGroupName: intrinsic-rg
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}